### PR TITLE
This is to add the prefix of the scatter-emphasised topics in the file names.

### PR DESCRIPTION
**Pull request by moomoofarm1**
The prefix is '0_scatter_emphasised'

### CODE REVIEW

**Comment by OscarKjell** [comment]
Briefly looking at the code, I wonder: do we really have to introduce a new parameter in topicsPlot() called popout? Isn't this exact information being given in scatter_legened_n? 

(maybe this parameter should be called sometihng like: emphasise_topics (and it will ensure these topics get the 0_ file name, and are emphasised (popout) in the scatter plot.

**Comment by moomoofarm1** [comment]
> Briefly looking at the code, I wonder: do we really have to introduce a new parameter in topicsPlot() called popout? Isn't this exact information being given in scatter_legened_n?
> 
> (maybe this parameter should be called sometihng like: emphasise_topics (and it will ensure these topics get the 0_ file name, and are emphasised (popout) in the scatter plot.

The function createPlot cannot know the specific popped-out topics through scatter_legend_n which only determines the number of popouts in each grid. And to save the topic files with a different names, the function createPlot in the deeper layer needs a transfer through parameters to know the exact topic number. So that's why I move the scatterlegend function before the running of topicsPlot1 to get the list of popped-out topics and then send the object to the topicsPlot1.

**Comment by OscarKjell** [comment]
Yes, but it looks like you are introducing a new parameter called pooout to the user in the topicsPlot function. Now it is set to NULL, right? And, what do you want the user to change NULL too, that you cannot get from scatter_legend_n?

**Comment by moomoofarm1** [comment]
> Yes, but it looks like you are introducing a new parameter called pooout to the user in the topicsPlot function. Now it is set to NULL, right? And, what do you want the user to change NULL too, that you cannot get from scatter_legend_n?

Oh, it should not be in the topicsPlot function. I will remove it.

**Pull request closed without merging**
